export const CountriesOptions = [
	{
		name: 'Afghanistan',
		code: 'AF',
		flag: 'flags/af.png',
		label: 'Afghanistan',
		value: 'Afghanistan',
	},
	{
		name: 'Albania',
		code: 'AL',
		flag: 'flags/al.png',
		label: 'Albania',
		value: 'Albania',
	},
	{
		name: 'Algeria',
		code: 'DZ',
		flag: 'flags/dz.png',
		label: 'Algeria',
		value: 'Algeria',
	},
	{
		name: 'American Samoa',
		code: 'AS',
		flag: 'flags/as.png',
		label: 'American Samoa',
		value: 'American Samoa',
	},
	{
		name: 'Andorra',
		code: 'AD',
		flag: 'flags/ad.png',
		label: 'Andorra',
		value: 'Andorra',
	},
	{
		name: 'Angola',
		code: 'AO',
		flag: 'flags/ao.png',
		label: 'Angola',
		value: 'Angola',
	},
	{
		name: 'Anguilla',
		code: 'AI',
		flag: 'flags/ai.png',
		label: 'Anguilla',
		value: 'Anguilla',
	},
	{
		name: 'Antarctica',
		code: 'AQ',
		flag: 'flags/aq.png',
		label: 'Antarctica',
		value: 'Antarctica',
	},
	{
		name: 'Antigua And Barbuda',
		code: 'AG',
		flag: 'flags/ag.png',
		label: 'Antigua And Barbuda',
		value: 'Antigua And Barbuda',
	},
	{
		name: 'Argentina',
		code: 'AR',
		flag: 'flags/ar.png',
		label: 'Argentina',
		value: 'Argentina',
	},
	{
		name: 'Armenia',
		code: 'AM',
		flag: 'flags/am.png',
		label: 'Armenia',
		value: 'Armenia',
	},
	{
		name: 'Aruba',
		code: 'AW',
		flag: 'flags/aw.png',
		label: 'Aruba',
		value: 'Aruba',
	},
	{
		name: 'Australia',
		code: 'AU',
		flag: 'flags/au.png',
		label: 'Australia',
		value: 'Australia',
	},
	{
		name: 'Austria',
		code: 'AT',
		flag: 'flags/at.png',
		label: 'Austria',
		value: 'Austria',
	},
	{
		name: 'Azerbaijan',
		code: 'AZ',
		flag: 'flags/az.png',
		label: 'Azerbaijan',
		value: 'Azerbaijan',
	},
	{
		name: 'Bolivia',
		code: 'BO',
		flag: 'flags/bo.png',
		label: 'Bolivia',
		value: 'Bolivia',
	},
	{
		name: 'Bouvet Island',
		code: 'BV',
		flag: 'flags/bv.png',
		label: 'Bouvet Island',
		value: 'Bouvet Island',
	},
	{
		name: 'Bahrain',
		code: 'BH',
		flag: 'flags/bh.png',
		label: 'Bahrain',
		value: 'Bahrain',
	},
	{
		name: 'Bangladesh',
		code: 'BD',
		flag: 'flags/bd.png',
		label: 'Bangladesh',
		value: 'Bangladesh',
	},
	{
		name: 'Barbados',
		code: 'BB',
		flag: 'flags/bb.png',
		label: 'Barbados',
		value: 'Barbados',
	},
	{
		name: 'Belarus',
		code: 'BY',
		flag: 'flags/by.png',
		label: 'Belarus',
		value: 'Belarus',
	},
	{
		name: 'Belgium',
		code: 'BE',
		flag: 'flags/be.png',
		label: 'Belgium',
		value: 'Belgium',
	},
	{
		name: 'Belize',
		code: 'BZ',
		flag: 'flags/bz.png',
		label: 'Belize',
		value: 'Belize',
	},
	{
		name: 'Benin',
		code: 'BJ',
		flag: 'flags/bj.png',
		label: 'Benin',
		value: 'Benin',
	},
	{
		name: 'Bermuda',
		code: 'BM',
		flag: 'flags/bm.png',
		label: 'Bermuda',
		value: 'Bermuda',
	},
	{
		name: 'Bhutan',
		code: 'BT',
		flag: 'flags/bt.png',
		label: 'Bhutan',
		value: 'Bhutan',
	},
	{
		name: 'Bosnia And Herzegovina',
		code: 'BA',
		flag: 'flags/ba.png',
		label: 'Bosnia And Herzegovina',
		value: 'Bosnia And Herzegovina',
	},
	{
		name: 'Botswana',
		code: 'BW',
		flag: 'flags/bw.png',
		label: 'Botswana',
		value: 'Botswana',
	},
	{
		name: 'Bahamas',
		code: 'BS',
		flag: 'flags/bs.png',
		label: 'Bahamas',
		value: 'Bahamas',
	},
	{
		name: 'Brazil',
		code: 'BR',
		flag: 'flags/br.png',
		label: 'Brazil',
		value: 'Brazil',
	},
	{
		name: 'British Indian Ocean Territory',
		code: 'IO',
		flag: 'flags/io.png',
		label: 'British Indian Ocean Territory',
		value: 'British Indian Ocean Territory',
	},
	{
		name: 'Brunei Darussalam',
		code: 'BN',
		flag: 'flags/bn.png',
		label: 'Brunei Darussalam',
		value: 'Brunei Darussalam',
	},
	{
		name: 'Bulgaria',
		code: 'BG',
		flag: 'flags/bg.png',
		label: 'Bulgaria',
		value: 'Bulgaria',
	},
	{
		name: 'Burkina Faso',
		code: 'BF',
		flag: 'flags/bf.png',
		label: 'Burkina Faso',
		value: 'Burkina Faso',
	},
	{
		name: 'Burundi',
		code: 'BI',
		flag: 'flags/bi.png',
		label: 'Burundi',
		value: 'Burundi',
	},
	{
		name: 'Czech Republic',
		code: 'CZ',
		flag: 'flags/cz.png',
		label: 'Czech Republic',
		value: 'Czech Republic',
	},
	{
		name: 'Cambodia',
		code: 'KH',
		flag: 'flags/kh.png',
		label: 'Cambodia',
		value: 'Cambodia',
	},
	{
		name: 'Cameroon',
		code: 'CM',
		flag: 'flags/cm.png',
		label: 'Cameroon',
		value: 'Cameroon',
	},
	{
		name: 'Canada',
		code: 'CA',
		flag: 'flags/ca.png',
		label: 'Canada',
		value: 'Canada',
	},
	{
		name: 'Cape Verde',
		code: 'CV',
		flag: 'flags/cv.png',
		label: 'Cape Verde',
		value: 'Cape Verde',
	},
	{
		name: 'Cayman Islands',
		code: 'KY',
		flag: 'flags/ky.png',
		label: 'Cayman Islands',
		value: 'Cayman Islands',
	},
	{
		name: 'Cuba',
		code: 'CU',
		flag: 'flags/cu.png',
		label: 'Cuba',
		value: 'Cuba',
	},
	{
		name: 'Chad',
		code: 'TD',
		flag: 'flags/td.png',
		label: 'Chad',
		value: 'Chad',
	},
	{
		name: 'Chile',
		code: 'CL',
		flag: 'flags/cl.png',
		label: 'Chile',
		value: 'Chile',
	},
	{
		name: 'China',
		code: 'CN',
		flag: 'flags/cn.png',
		label: 'China',
		value: 'China',
	},
	{
		name: 'Christmas Island',
		code: 'CX',
		flag: 'flags/cx.png',
		label: 'Christmas Island',
		value: 'Christmas Island',
	},
	{
		name: 'Cocos (keeling) Islands',
		code: 'CC',
		flag: 'flags/cc.png',
		label: 'Cocos (keeling) Islands',
		value: 'Cocos (keeling) Islands',
	},
	{
		name: 'Colombia',
		code: 'CO',
		flag: 'flags/co.png',
		label: 'Colombia',
		value: 'Colombia',
	},
	{
		name: 'Comoros',
		code: 'KM',
		flag: 'flags/km.png',
		label: 'Comoros',
		value: 'Comoros',
	},
	{
		name: 'Congo',
		code: 'CG',
		flag: 'flags/cg.png',
		label: 'Congo',
		value: 'Congo',
	},
	{
		name: 'Cyprus',
		code: 'CY',
		flag: 'flags/cy.png',
		label: 'Cyprus',
		value: 'Cyprus',
	},
	{
		name: 'Cook Islands',
		code: 'CK',
		flag: 'flags/ck.png',
		label: 'Cook Islands',
		value: 'Cook Islands',
	},
	{
		name: 'Costa Rica',
		code: 'CR',
		flag: 'flags/cr.png',
		label: 'Costa Rica',
		value: 'Costa Rica',
	},
	{
		name: "Cote D'ivoire",
		code: 'CI',
		flag: 'flags/ci.png',
		label: "Cote D'ivoire",
		value: "Cote D'ivoire",
	},
	{
		name: 'Croatia',
		code: 'HR',
		flag: 'flags/hr.png',
		label: 'Croatia',
		value: 'Croatia',
	},
	{
		name: 'Central African Republic',
		code: 'CF',
		flag: 'flags/cf.png',
		label: 'Central African Republic',
		value: 'Central African Republic',
	},
	{
		name: 'Congo, The Democratic Republic Of The',
		code: 'CD',
		flag: 'flags/cd.png',
		label: 'Congo, The Democratic Republic Of The',
		value: 'Congo, The Democratic Republic Of The',
	},
	{
		name: 'Denmark',
		code: 'DK',
		flag: 'flags/dk.png',
		label: 'Denmark',
		value: 'Denmark',
	},
	{
		name: 'Djibouti',
		code: 'DJ',
		flag: 'flags/dj.png',
		label: 'Djibouti',
		value: 'Djibouti',
	},
	{
		name: 'Dominica',
		code: 'DM',
		flag: 'flags/dm.png',
		label: 'Dominica',
		value: 'Dominica',
	},
	{
		name: 'Dominican Republic',
		code: 'DO',
		flag: 'flags/do.png',
		label: 'Dominican Republic',
		value: 'Dominican Republic',
	},
	{
		name: 'Eswatini',
		code: 'SZ',
		flag: 'flags/sz.png',
		label: 'Eswatini',
		value: 'Eswatini',
	},
	{
		name: 'Ecuador',
		code: 'EC',
		flag: 'flags/ec.png',
		label: 'Ecuador',
		value: 'Ecuador',
	},
	{
		name: 'Egypt',
		code: 'EG',
		flag: 'flags/eg.png',
		label: 'Egypt',
		value: 'Egypt',
	},
	{
		name: 'El Salvador',
		code: 'SV',
		flag: 'flags/sv.png',
		label: 'El Salvador',
		value: 'El Salvador',
	},
	{
		name: 'Equatorial Guinea',
		code: 'GQ',
		flag: 'flags/gq.png',
		label: 'Equatorial Guinea',
		value: 'Equatorial Guinea',
	},
	{
		name: 'Eritrea',
		code: 'ER',
		flag: 'flags/er.png',
		label: 'Eritrea',
		value: 'Eritrea',
	},
	{
		name: 'Estonia',
		code: 'EE',
		flag: 'flags/ee.png',
		label: 'Estonia',
		value: 'Estonia',
	},
	{
		name: 'Ethiopia',
		code: 'ET',
		flag: 'flags/et.png',
		label: 'Ethiopia',
		value: 'Ethiopia',
	},
	{
		name: 'Falkland Islands (malvinas)',
		code: 'FK',
		flag: 'flags/fk.png',
		label: 'Falkland Islands (malvinas)',
		value: 'Falkland Islands (malvinas)',
	},
	{
		name: 'Faroe Islands',
		code: 'FO',
		flag: 'flags/fo.png',
		label: 'Faroe Islands',
		value: 'Faroe Islands',
	},
	{
		name: 'Fiji',
		code: 'FJ',
		flag: 'flags/fj.png',
		label: 'Fiji',
		value: 'Fiji',
	},
	{
		name: 'Finland',
		code: 'FI',
		flag: 'flags/fi.png',
		label: 'Finland',
		value: 'Finland',
	},
	{
		name: 'France',
		code: 'FR',
		flag: 'flags/fr.png',
		label: 'France',
		value: 'France',
	},
	{
		name: 'French Guiana',
		code: 'GF',
		flag: 'flags/gf.png',
		label: 'French Guiana',
		value: 'French Guiana',
	},
	{
		name: 'French Polynesia',
		code: 'PF',
		flag: 'flags/pf.png',
		label: 'French Polynesia',
		value: 'French Polynesia',
	},
	{
		name: 'French Southern Territories',
		code: 'TF',
		flag: 'flags/tf.png',
		label: 'French Southern Territories',
		value: 'French Southern Territories',
	},
	{
		name: 'Ghana',
		code: 'GH',
		flag: 'flags/gh.png',
		label: 'Ghana',
		value: 'Ghana',
	},
	{
		name: 'Gambia',
		code: 'GM',
		flag: 'flags/gm.png',
		label: 'Gambia',
		value: 'Gambia',
	},
	{
		name: 'Georgia',
		code: 'GE',
		flag: 'flags/ge.png',
		label: 'Georgia',
		value: 'Georgia',
	},
	{
		name: 'Germany',
		code: 'DE',
		flag: 'flags/de.png',
		label: 'Germany',
		value: 'Germany',
	},
	{
		name: 'Gabon',
		code: 'GA',
		flag: 'flags/ga.png',
		label: 'Gabon',
		value: 'Gabon',
	},
	{
		name: 'Gibraltar',
		code: 'GI',
		flag: 'flags/gi.png',
		label: 'Gibraltar',
		value: 'Gibraltar',
	},
	{
		name: 'Greece',
		code: 'GR',
		flag: 'flags/gr.png',
		label: 'Greece',
		value: 'Greece',
	},
	{
		name: 'Greenland',
		code: 'GL',
		flag: 'flags/gl.png',
		label: 'Greenland',
		value: 'Greenland',
	},
	{
		name: 'Grenada',
		code: 'GD',
		flag: 'flags/gd.png',
		label: 'Grenada',
		value: 'Grenada',
	},
	{
		name: 'Guadeloupe',
		code: 'GP',
		flag: 'flags/gp.png',
		label: 'Guadeloupe',
		value: 'Guadeloupe',
	},
	{
		name: 'Guam',
		code: 'GU',
		flag: 'flags/gu.png',
		label: 'Guam',
		value: 'Guam',
	},
	{
		name: 'Guatemala',
		code: 'GT',
		flag: 'flags/gt.png',
		label: 'Guatemala',
		value: 'Guatemala',
	},
	{
		name: 'Guernsey',
		code: 'GG',
		flag: 'flags/gg.png',
		label: 'Guernsey',
		value: 'Guernsey',
	},
	{
		name: 'Guinea',
		code: 'GN',
		flag: 'flags/gn.png',
		label: 'Guinea',
		value: 'Guinea',
	},
	{
		name: 'Guinea-bissau',
		code: 'GW',
		flag: 'flags/gw.png',
		label: 'Guinea-bissau',
		value: 'Guinea-bissau',
	},
	{
		name: 'Guyana',
		code: 'GY',
		flag: 'flags/gy.png',
		label: 'Guyana',
		value: 'Guyana',
	},
	{
		name: 'Haiti',
		code: 'HT',
		flag: 'flags/ht.png',
		label: 'Haiti',
		value: 'Haiti',
	},
	{
		name: 'Heard Island And Mcdonald Islands',
		code: 'HM',
		flag: 'flags/hm.png',
		label: 'Heard Island And Mcdonald Islands',
		value: 'Heard Island And Mcdonald Islands',
	},
	{
		name: 'Holy See (vatican City State)',
		code: 'VA',
		flag: 'flags/va.png',
		label: 'Holy See (vatican City State)',
		value: 'Holy See (vatican City State)',
	},
	{
		name: 'Honduras',
		code: 'HN',
		flag: 'flags/hn.png',
		label: 'Honduras',
		value: 'Honduras',
	},
	{
		name: 'Hong Kong',
		code: 'HK',
		flag: 'flags/hk.png',
		label: 'Hong Kong',
		value: 'Hong Kong',
	},
	{
		name: 'Hungary',
		code: 'HU',
		flag: 'flags/hu.png',
		label: 'Hungary',
		value: 'Hungary',
	},
	{
		name: 'Israel',
		code: 'IL',
		flag: 'flags/il.png',
		label: 'Israel',
		value: 'Israel',
	},
	{
		name: 'Indonesia',
		code: 'ID',
		flag: 'flags/id.png',
		label: 'Indonesia',
		value: 'Indonesia',
	},
	{
		name: 'Iran, Islamic Republic Of',
		code: 'IR',
		flag: 'flags/ir.png',
		label: 'Iran, Islamic Republic Of',
		value: 'Iran, Islamic Republic Of',
	},
	{
		name: 'Iraq',
		code: 'IQ',
		flag: 'flags/iq.png',
		label: 'Iraq',
		value: 'Iraq',
	},
	{
		name: 'Ireland',
		code: 'IE',
		flag: 'flags/ie.png',
		label: 'Ireland',
		value: 'Ireland',
	},
	{
		name: 'Isle Of Man',
		code: 'IM',
		flag: 'flags/im.png',
		label: 'Isle Of Man',
		value: 'Isle Of Man',
	},
	{
		name: 'Iceland',
		code: 'IS',
		flag: 'flags/is.png',
		label: 'Iceland',
		value: 'Iceland',
	},
	{
		name: 'Italy',
		code: 'IT',
		flag: 'flags/it.png',
		label: 'Italy',
		value: 'Italy',
	},
	{
		name: 'India',
		code: 'IN',
		flag: 'flags/in.png',
		label: 'India',
		value: 'India',
	},
	{
		name: 'Jamaica',
		code: 'JM',
		flag: 'flags/jm.png',
		label: 'Jamaica',
		value: 'Jamaica',
	},
	{
		name: 'Japan',
		code: 'JP',
		flag: 'flags/jp.png',
		label: 'Japan',
		value: 'Japan',
	},
	{
		name: 'Jersey',
		code: 'JE',
		flag: 'flags/je.png',
		label: 'Jersey',
		value: 'Jersey',
	},
	{
		name: 'Jordan',
		code: 'JO',
		flag: 'flags/jo.png',
		label: 'Jordan',
		value: 'Jordan',
	},
	{
		name: 'Kyrgyzstan',
		code: 'KG',
		flag: 'flags/kg.png',
		label: 'Kyrgyzstan',
		value: 'Kyrgyzstan',
	},
	{
		name: 'Kazakhstan',
		code: 'KZ',
		flag: 'flags/kz.png',
		label: 'Kazakhstan',
		value: 'Kazakhstan',
	},
	{
		name: 'Kenya',
		code: 'KE',
		flag: 'flags/ke.png',
		label: 'Kenya',
		value: 'Kenya',
	},
	{
		name: 'Kiribati',
		code: 'KI',
		flag: 'flags/ki.png',
		label: 'Kiribati',
		value: 'Kiribati',
	},
	{
		name: 'Kosovo',
		code: 'XK',
		flag: 'flags/xk.png',
		label: 'Kosovo',
		value: 'Kosovo',
	},
	{
		name: 'Kuwait',
		code: 'KW',
		flag: 'flags/kw.png',
		label: 'Kuwait',
		value: 'Kuwait',
	},
	{
		name: 'Lesotho',
		code: 'LS',
		flag: 'flags/ls.png',
		label: 'Lesotho',
		value: 'Lesotho',
	},
	{
		name: "Lao People's Democratic Republic",
		code: 'LA',
		flag: 'flags/la.png',
		label: "Lao People's Democratic Republic",
		value: "Lao People's Democratic Republic",
	},
	{
		name: 'Latvia',
		code: 'LV',
		flag: 'flags/lv.png',
		label: 'Latvia',
		value: 'Latvia',
	},
	{
		name: 'Lebanon',
		code: 'LB',
		flag: 'flags/lb.png',
		label: 'Lebanon',
		value: 'Lebanon',
	},
	{
		name: 'Liberia',
		code: 'LR',
		flag: 'flags/lr.png',
		label: 'Liberia',
		value: 'Liberia',
	},
	{
		name: 'Libya',
		code: 'LY',
		flag: 'flags/ly.png',
		label: 'Libya',
		value: 'Libya',
	},
	{
		name: 'Liechtenstein',
		code: 'LI',
		flag: 'flags/li.png',
		label: 'Liechtenstein',
		value: 'Liechtenstein',
	},
	{
		name: 'Lithuania',
		code: 'LT',
		flag: 'flags/lt.png',
		label: 'Lithuania',
		value: 'Lithuania',
	},
	{
		name: 'Luxembourg',
		code: 'LU',
		flag: 'flags/lu.png',
		label: 'Luxembourg',
		value: 'Luxembourg',
	},
	{
		name: 'Mozambique',
		code: 'MZ',
		flag: 'flags/mz.png',
		label: 'Mozambique',
		value: 'Mozambique',
	},
	{
		name: 'Myanmar',
		code: 'MM',
		flag: 'flags/mm.png',
		label: 'Myanmar',
		value: 'Myanmar',
	},
	{
		name: 'Macao',
		code: 'MO',
		flag: 'flags/mo.png',
		label: 'Macao',
		value: 'Macao',
	},
	{
		name: 'Morocco',
		code: 'MA',
		flag: 'flags/ma.png',
		label: 'Morocco',
		value: 'Morocco',
	},
	{
		name: 'Montenegro',
		code: 'ME',
		flag: 'flags/me.png',
		label: 'Montenegro',
		value: 'Montenegro',
	},
	{
		name: 'Malawi',
		code: 'MW',
		flag: 'flags/mw.png',
		label: 'Malawi',
		value: 'Malawi',
	},
	{
		name: 'Malaysia',
		code: 'MY',
		flag: 'flags/my.png',
		label: 'Malaysia',
		value: 'Malaysia',
	},
	{
		name: 'Maldives',
		code: 'MV',
		flag: 'flags/mv.png',
		label: 'Maldives',
		value: 'Maldives',
	},
	{
		name: 'Mali',
		code: 'ML',
		flag: 'flags/ml.png',
		label: 'Mali',
		value: 'Mali',
	},
	{
		name: 'Malta',
		code: 'MT',
		flag: 'flags/mt.png',
		label: 'Malta',
		value: 'Malta',
	},
	{
		name: 'Marshall Islands',
		code: 'MH',
		flag: 'flags/mh.png',
		label: 'Marshall Islands',
		value: 'Marshall Islands',
	},
	{
		name: 'Martinique',
		code: 'MQ',
		flag: 'flags/mq.png',
		label: 'Martinique',
		value: 'Martinique',
	},
	{
		name: 'Mauritania',
		code: 'MR',
		flag: 'flags/mr.png',
		label: 'Mauritania',
		value: 'Mauritania',
	},
	{
		name: 'Mauritius',
		code: 'MU',
		flag: 'flags/mu.png',
		label: 'Mauritius',
		value: 'Mauritius',
	},
	{
		name: 'Mayotte',
		code: 'YT',
		flag: 'flags/yt.png',
		label: 'Mayotte',
		value: 'Mayotte',
	},
	{
		name: 'Mexico',
		code: 'MX',
		flag: 'flags/mx.png',
		label: 'Mexico',
		value: 'Mexico',
	},
	{
		name: 'Micronesia, Federated States Of',
		code: 'FM',
		flag: 'flags/fm.png',
		label: 'Micronesia, Federated States Of',
		value: 'Micronesia, Federated States Of',
	},
	{
		name: 'Moldova, Republic Of',
		code: 'MD',
		flag: 'flags/md.png',
		label: 'Moldova, Republic Of',
		value: 'Moldova, Republic Of',
	},
	{
		name: 'Monaco',
		code: 'MC',
		flag: 'flags/mc.png',
		label: 'Monaco',
		value: 'Monaco',
	},
	{
		name: 'Montserrat',
		code: 'MS',
		flag: 'flags/ms.png',
		label: 'Montserrat',
		value: 'Montserrat',
	},
	{
		name: 'Madagascar',
		code: 'MG',
		flag: 'flags/mg.png',
		label: 'Madagascar',
		value: 'Madagascar',
	},
	{
		name: 'Mongolia',
		code: 'MN',
		flag: 'flags/mn.png',
		label: 'Mongolia',
		value: 'Mongolia',
	},
	{
		name: 'North Macedonia, Republic Of',
		code: 'MK',
		flag: 'flags/mk.png',
		label: 'North Macedonia, Republic Of',
		value: 'North Macedonia, Republic Of',
	},
	{
		name: 'Norway',
		code: 'NO',
		flag: 'flags/no.png',
		label: 'Norway',
		value: 'Norway',
	},
	{
		name: 'North Korea',
		code: 'KP',
		flag: 'flags/kp.png',
		label: 'North Korea',
		value: 'North Korea',
	},
	{
		name: 'Namibia',
		code: 'NA',
		flag: 'flags/na.png',
		label: 'Namibia',
		value: 'Namibia',
	},
	{
		name: 'Nauru',
		code: 'NR',
		flag: 'flags/nr.png',
		label: 'Nauru',
		value: 'Nauru',
	},
	{
		name: 'Nepal',
		code: 'NP',
		flag: 'flags/np.png',
		label: 'Nepal',
		value: 'Nepal',
	},
	{
		name: 'Netherlands',
		code: 'NL',
		flag: 'flags/nl.png',
		label: 'Netherlands',
		value: 'Netherlands',
	},
	{
		name: 'Netherlands Antilles',
		code: 'AN',
		flag: 'flags/an.png',
		label: 'Netherlands Antilles',
		value: 'Netherlands Antilles',
	},
	{
		name: 'New Caledonia',
		code: 'NC',
		flag: 'flags/nc.png',
		label: 'New Caledonia',
		value: 'New Caledonia',
	},
	{
		name: 'New Zealand',
		code: 'NZ',
		flag: 'flags/nz.png',
		label: 'New Zealand',
		value: 'New Zealand',
	},
	{
		name: 'Nicaragua',
		code: 'NI',
		flag: 'flags/ni.png',
		label: 'Nicaragua',
		value: 'Nicaragua',
	},
	{
		name: 'Niger',
		code: 'NE',
		flag: 'flags/ne.png',
		label: 'Niger',
		value: 'Niger',
	},
	{
		name: 'Nigeria',
		code: 'NG',
		flag: 'flags/ng.png',
		label: 'Nigeria',
		value: 'Nigeria',
	},
	{
		name: 'Niue',
		code: 'NU',
		flag: 'flags/nu.png',
		label: 'Niue',
		value: 'Niue',
	},
	{
		name: 'Northern Mariana Islands',
		code: 'MP',
		flag: 'flags/mp.png',
		label: 'Northern Mariana Islands',
		value: 'Northern Mariana Islands',
	},
	{
		name: 'Norfolk Island',
		code: 'NF',
		flag: 'flags/nf.png',
		label: 'Norfolk Island',
		value: 'Norfolk Island',
	},
	{
		name: 'Oman',
		code: 'OM',
		flag: 'flags/om.png',
		label: 'Oman',
		value: 'Oman',
	},
	{
		name: 'Pakistan',
		code: 'PK',
		flag: 'flags/pk.png',
		label: 'Pakistan',
		value: 'Pakistan',
	},
	{
		name: 'Palau',
		code: 'PW',
		flag: 'flags/pw.png',
		label: 'Palau',
		value: 'Palau',
	},
	{
		name: 'Panama',
		code: 'PA',
		flag: 'flags/pa.png',
		label: 'Panama',
		value: 'Panama',
	},
	{
		name: 'Papua New Guinea',
		code: 'PG',
		flag: 'flags/pg.png',
		label: 'Papua New Guinea',
		value: 'Papua New Guinea',
	},
	{
		name: 'Paraguay',
		code: 'PY',
		flag: 'flags/py.png',
		label: 'Paraguay',
		value: 'Paraguay',
	},
	{
		name: 'Peru',
		code: 'PE',
		flag: 'flags/pe.png',
		label: 'Peru',
		value: 'Peru',
	},
	{
		name: 'Philippines',
		code: 'PH',
		flag: 'flags/ph.png',
		label: 'Philippines',
		value: 'Philippines',
	},
	{
		name: 'Pitcairn',
		code: 'PN',
		flag: 'flags/pn.png',
		label: 'Pitcairn',
		value: 'Pitcairn',
	},
	{
		name: 'Poland',
		code: 'PL',
		flag: 'flags/pl.png',
		label: 'Poland',
		value: 'Poland',
	},
	{
		name: 'Portugal',
		code: 'PT',
		flag: 'flags/pt.png',
		label: 'Portugal',
		value: 'Portugal',
	},
	{
		name: 'Puerto Rico',
		code: 'PR',
		flag: 'flags/pr.png',
		label: 'Puerto Rico',
		value: 'Puerto Rico',
	},
	{
		name: 'Qatar',
		code: 'QA',
		flag: 'flags/qa.png',
		label: 'Qatar',
		value: 'Qatar',
	},
	{
		name: 'Reunion',
		code: 'RE',
		flag: 'flags/re.png',
		label: 'Reunion',
		value: 'Reunion',
	},
	{
		name: 'Romania',
		code: 'RO',
		flag: 'flags/ro.png',
		label: 'Romania',
		value: 'Romania',
	},
	{
		name: 'Russian Federation, Russia',
		code: 'RU',
		flag: 'flags/ru.png',
		label: 'Russian Federation, Russia',
		value: 'Russian Federation, Russia',
	},
	{
		name: 'Rwanda',
		code: 'RW',
		flag: 'flags/rw.png',
		label: 'Rwanda',
		value: 'Rwanda',
	},
	{
		name: 'San Marino',
		code: 'SM',
		flag: 'flags/sm.png',
		label: 'San Marino',
		value: 'San Marino',
	},
	{
		name: 'Sierra Leone',
		code: 'SL',
		flag: 'flags/sl.png',
		label: 'Sierra Leone',
		value: 'Sierra Leone',
	},
	{
		name: 'Saint Barthélemy',
		code: 'BL',
		flag: 'flags/bl.png',
		label: 'Saint Barthélemy',
		value: 'Saint Barthélemy',
	},
	{
		name: 'Saint Helena',
		code: 'SH',
		flag: 'flags/sh.png',
		label: 'Saint Helena',
		value: 'Saint Helena',
	},
	{
		name: 'Saint Kitts And Nevis',
		code: 'KN',
		flag: 'flags/kn.png',
		label: 'Saint Kitts And Nevis',
		value: 'Saint Kitts And Nevis',
	},
	{
		name: 'Saint Lucia',
		code: 'LC',
		flag: 'flags/lc.png',
		label: 'Saint Lucia',
		value: 'Saint Lucia',
	},
	{
		name: 'Saint Martin (french Part)',
		code: 'MF',
		flag: 'flags/mf.png',
		label: 'Saint Martin (french Part)',
		value: 'Saint Martin (french Part)',
	},
	{
		name: 'Saint Pierre And Miquelon',
		code: 'PM',
		flag: 'flags/pm.png',
		label: 'Saint Pierre And Miquelon',
		value: 'Saint Pierre And Miquelon',
	},
	{
		name: 'Saint Vincent And The Grenadines',
		code: 'VC',
		flag: 'flags/vc.png',
		label: 'Saint Vincent And The Grenadines',
		value: 'Saint Vincent And The Grenadines',
	},
	{
		name: 'Samoa',
		code: 'WS',
		flag: 'flags/ws.png',
		label: 'Samoa',
		value: 'Samoa',
	},
	{
		name: 'South Korea',
		code: 'KR',
		flag: 'flags/kr.png',
		label: 'South Korea',
		value: 'South Korea',
	},
	{
		name: 'Sao Tome And Principe',
		code: 'ST',
		flag: 'flags/st.png',
		label: 'Sao Tome And Principe',
		value: 'Sao Tome And Principe',
	},
	{
		name: 'Saudi Arabia',
		code: 'SA',
		flag: 'flags/sa.png',
		label: 'Saudi Arabia',
		value: 'Saudi Arabia',
	},
	{
		name: 'Senegal',
		code: 'SN',
		flag: 'flags/sn.png',
		label: 'Senegal',
		value: 'Senegal',
	},
	{
		name: 'Serbia',
		code: 'RS',
		flag: 'flags/rs.png',
		label: 'Serbia',
		value: 'Serbia',
	},
	{
		name: 'Seychelles',
		code: 'SC',
		flag: 'flags/sc.png',
		label: 'Seychelles',
		value: 'Seychelles',
	},
	{
		name: 'State Of Palestine, Palestine',
		code: 'PS',
		flag: 'flags/ps.png',
		label: 'State Of Palestine, Palestine',
		value: 'State Of Palestine, Palestine',
	},
	{
		name: 'Singapore',
		code: 'SG',
		flag: 'flags/sg.png',
		label: 'Singapore',
		value: 'Singapore',
	},
	{
		name: 'Slovakia',
		code: 'SK',
		flag: 'flags/sk.png',
		label: 'Slovakia',
		value: 'Slovakia',
	},
	{
		name: 'Slovenia',
		code: 'SI',
		flag: 'flags/si.png',
		label: 'Slovenia',
		value: 'Slovenia',
	},
	{
		name: 'Solomon Islands',
		code: 'SB',
		flag: 'flags/sb.png',
		label: 'Solomon Islands',
		value: 'Solomon Islands',
	},
	{
		name: 'Somalia',
		code: 'SO',
		flag: 'flags/so.png',
		label: 'Somalia',
		value: 'Somalia',
	},
	{
		name: 'South Africa',
		code: 'ZA',
		flag: 'flags/za.png',
		label: 'South Africa',
		value: 'South Africa',
	},
	{
		name: 'South Sudan',
		code: 'SS',
		flag: 'flags/ss.png',
		label: 'South Sudan',
		value: 'South Sudan',
	},
	{
		name: 'South Georgia And The South Sandwich Islands',
		code: 'GS',
		flag: 'flags/gs.png',
		label: 'South Georgia And The South Sandwich Islands',
		value: 'South Georgia And The South Sandwich Islands',
	},
	{
		name: 'Spain',
		code: 'ES',
		flag: 'flags/es.png',
		label: 'Spain',
		value: 'Spain',
	},
	{
		name: 'Sri Lanka',
		code: 'LK',
		flag: 'flags/lk.png',
		label: 'Sri Lanka',
		value: 'Sri Lanka',
	},
	{
		name: 'Sudan',
		code: 'SD',
		flag: 'flags/sd.png',
		label: 'Sudan',
		value: 'Sudan',
	},
	{
		name: 'Suriname',
		code: 'SR',
		flag: 'flags/sr.png',
		label: 'Suriname',
		value: 'Suriname',
	},
	{
		name: 'Svalbard And Jan Mayen',
		code: 'SJ',
		flag: 'flags/sj.png',
		label: 'Svalbard And Jan Mayen',
		value: 'Svalbard And Jan Mayen',
	},
	{
		name: 'Sweden',
		code: 'SE',
		flag: 'flags/se.png',
		label: 'Sweden',
		value: 'Sweden',
	},
	{
		name: 'Switzerland',
		code: 'CH',
		flag: 'flags/ch.png',
		label: 'Switzerland',
		value: 'Switzerland',
	},
	{
		name: 'Syrian Arab Republic',
		code: 'SY',
		flag: 'flags/sy.png',
		label: 'Syrian Arab Republic',
		value: 'Syrian Arab Republic',
	},
	{
		name: 'Turkmenistan',
		code: 'TM',
		flag: 'flags/tm.png',
		label: 'Turkmenistan',
		value: 'Turkmenistan',
	},
	{
		name: 'Taiwan, Province Of China, Taiwan',
		code: 'TW',
		flag: 'flags/tw.png',
		label: 'Taiwan, Province Of China, Taiwan',
		value: 'Taiwan, Province Of China, Taiwan',
	},
	{
		name: 'Tajikistan',
		code: 'TJ',
		flag: 'flags/tj.png',
		label: 'Tajikistan',
		value: 'Tajikistan',
	},
	{
		name: 'Turks And Caicos Islands',
		code: 'TC',
		flag: 'flags/tc.png',
		label: 'Turks And Caicos Islands',
		value: 'Turks And Caicos Islands',
	},
	{
		name: 'Thailand',
		code: 'TH',
		flag: 'flags/th.png',
		label: 'Thailand',
		value: 'Thailand',
	},
	{
		name: 'Timor-leste',
		code: 'TL',
		flag: 'flags/tl.png',
		label: 'Timor-leste',
		value: 'Timor-leste',
	},
	{
		name: 'Togo',
		code: 'TG',
		flag: 'flags/tg.png',
		label: 'Togo',
		value: 'Togo',
	},
	{
		name: 'Tokelau',
		code: 'TK',
		flag: 'flags/tk.png',
		label: 'Tokelau',
		value: 'Tokelau',
	},
	{
		name: 'Tonga',
		code: 'TO',
		flag: 'flags/to.png',
		label: 'Tonga',
		value: 'Tonga',
	},
	{
		name: 'Trinidad And Tobago',
		code: 'TT',
		flag: 'flags/tt.png',
		label: 'Trinidad And Tobago',
		value: 'Trinidad And Tobago',
	},
	{
		name: 'Tunisia',
		code: 'TN',
		flag: 'flags/tn.png',
		label: 'Tunisia',
		value: 'Tunisia',
	},
	{
		name: 'Turkey',
		code: 'TR',
		flag: 'flags/tr.png',
		label: 'Turkey',
		value: 'Turkey',
	},
	{
		name: 'Tuvalu',
		code: 'TV',
		flag: 'flags/tv.png',
		label: 'Tuvalu',
		value: 'Tuvalu',
	},
	{
		name: 'Tanzania, United Republic Of',
		code: 'TZ',
		flag: 'flags/tz.png',
		label: 'Tanzania, United Republic Of',
		value: 'Tanzania, United Republic Of',
	},
	{
		name: 'Uganda',
		code: 'UG',
		flag: 'flags/ug.png',
		label: 'Uganda',
		value: 'Uganda',
	},
	{
		name: 'Ukraine',
		code: 'UA',
		flag: 'flags/ua.png',
		label: 'Ukraine',
		value: 'Ukraine',
	},
	{
		name: 'United Arab Emirates',
		code: 'AE',
		flag: 'flags/ae.png',
		label: 'United Arab Emirates',
		value: 'United Arab Emirates',
	},
	{
		name: 'United Kingdom, Uk, Great Britain',
		code: 'GB',
		flag: 'flags/gb.png',
		label: 'United Kingdom, Uk, Great Britain',
		value: 'United Kingdom, Uk, Great Britain',
	},
	{
		name: 'United States Of America, Usa',
		code: 'US',
		flag: 'flags/us.png',
		label: 'United States Of America, Usa',
		value: 'United States Of America, Usa',
	},
	{
		name: 'Uruguay',
		code: 'UY',
		flag: 'flags/uy.png',
		label: 'Uruguay',
		value: 'Uruguay',
	},
	{
		name: 'Uzbekistan',
		code: 'UZ',
		flag: 'flags/uz.png',
		label: 'Uzbekistan',
		value: 'Uzbekistan',
	},
	{
		name: 'Vanuatu',
		code: 'VU',
		flag: 'flags/vu.png',
		label: 'Vanuatu',
		value: 'Vanuatu',
	},
	{
		name: 'Venezuela',
		code: 'VE',
		flag: 'flags/ve.png',
		label: 'Venezuela',
		value: 'Venezuela',
	},
	{
		name: 'Vietnam',
		code: 'VN',
		flag: 'flags/vn.png',
		label: 'Vietnam',
		value: 'Vietnam',
	},
	{
		name: 'Virgin Islands, British',
		code: 'VG',
		flag: 'flags/vg.png',
		label: 'Virgin Islands, British',
		value: 'Virgin Islands, British',
	},
	{
		name: 'Virgin Islands, U.s.',
		code: 'VI',
		flag: 'flags/vi.png',
		label: 'Virgin Islands, U.s.',
		value: 'Virgin Islands, U.s.',
	},
	{
		name: 'Wallis And Futuna',
		code: 'WF',
		flag: 'flags/wf.png',
		label: 'Wallis And Futuna',
		value: 'Wallis And Futuna',
	},
	{
		name: 'Yemen',
		code: 'YE',
		flag: 'flags/ye.png',
		label: 'Yemen',
		value: 'Yemen',
	},
	{
		name: 'Zambia',
		code: 'ZM',
		flag: 'flags/zm.png',
		label: 'Zambia',
		value: 'Zambia',
	},
	{
		name: 'Zimbabwe',
		code: 'ZW',
		flag: 'flags/zw.png',
		label: 'Zimbabwe',
		value: 'Zimbabwe',
	},
	{
		name: 'Åland Islands',
		code: 'AX',
		flag: 'flags/ax.png',
		label: 'Åland Islands',
		value: 'Åland Islands',
	},
].map((i) => ({
	...i,
	label: (
		<div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
			<span className={`flag:${i.code}`}></span>
			<span>{i.name}</span>
		</div>
	),
}))
export const mappingCountriesOptions = CountriesOptions.reduce((obj, item) => {
	obj[item.code] = item
	return obj
}, {})
