import type { Metadata } from 'next'

type Props = {
	params: Promise<{ id: string }>
}
const data: Metadata[] = [
	{
		title: 'Create Next App1',
		description: 'Generated by create next app',
		openGraph: {
			title: 'THIS IS DEMO SEO ON huteo',
			url: 'https://firebasestorage.googleapis.com/v0/b/fir-5f468.appspot.com/o/ponk.jpg?alt=media&token=64c0afa3-9797-46a6-80cf-a90e5cf74027',
			images: [
				{
					url: 'https://firebasestorage.googleapis.com/v0/b/fir-5f468.appspot.com/o/ponk.jpg?alt=media&token=64c0afa3-9797-46a6-80cf-a90e5cf74027',
					alt: 'this is huteo',
					height: 314,
					width: 600,
				},
			],
			type: 'website',
		},
	},
	{
		title: 'Create Next App2',
		description: 'Generated by create next app',
		openGraph: {
			title: 'THIS IS DEMO SEO ON whoteo',
			url: 'https://firebasestorage.googleapis.com/v0/b/fir-5f468.appspot.com/o/like.jpg?alt=media&token=e298a180-26be-40ef-b91e-cdb7467ae959',
			images: [
				{
					url: 'https://firebasestorage.googleapis.com/v0/b/fir-5f468.appspot.com/o/like.jpg?alt=media&token=e298a180-26be-40ef-b91e-cdb7467ae959',
					alt: 'this is whoteo ',
					height: 314,
					width: 600,
				},
			],
			type: 'website',
		},
	},
	{
		title: 'Create Next App3',
		description: 'Generated by create next app',
		openGraph: {
			title: 'THIS IS DEMO SEO ON dandelion',
			url: 'https://firebasestorage.googleapis.com/v0/b/fir-5f468.appspot.com/o/hoa.jpg?alt=media&token=4c405dcf-ed46-44fe-a5a2-8c58bee20c06',
			images: [
				{
					url: 'https://firebasestorage.googleapis.com/v0/b/fir-5f468.appspot.com/o/hoa.jpg?alt=media&token=4c405dcf-ed46-44fe-a5a2-8c58bee20c06',
					alt: 'this is dandelion',
					height: 314,
					width: 600,
				},
			],
			type: 'website',
		},
	},
]
export async function generateMetadata({ params }: Props): Promise<Metadata> {
	// read route params
	const id = (await params).id
	console.log('🎇🧧🧧🧧🎇 TrieuNinhHan ~ generateMetadata ~ id:', id)

	// fetch data

	// optionally access and extend (rather than replace) parent metadata

	return {
		...data[Number(id || 0)],
	}
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return <b>{children}</b>
}
