export const mainRoutes = {
	home: '/overview',
	login: 'login',
	forgetPassword: 'forget-password',
	policyTerm: 'policy-term',
	register: 'register',
	hangout: 'hangout',
	community: 'community',
	event: 'event',
	upcomingEvent: 'upcoming-event',
	discussions: 'discussion',
	overview: 'overview',
	search: 'search',
	inbox: 'inbox',
	friend: 'friend',
	dating: 'dating',
	profile: 'profile',
	exploreInterest: 'explore-interest',
	chatRoom: 'chat-room',
}
