import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { headers } from 'next/headers'
import { appLayoutExclusive } from './variable/layoutData'
import { AntdRegistry } from '@ant-design/nextjs-registry'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	openGraph: {
		title: 'THIS IS DEMO SEO ON FACEBOOK',
		url: 'https://firebasestorage.googleapis.com/v0/b/fir-5f468.appspot.com/o/hoa.jpg?alt=media&token=4c405dcf-ed46-44fe-a5a2-8c58bee20c06',
		images: [
			{
				url: 'https://firebasestorage.googleapis.com/v0/b/fir-5f468.appspot.com/o/hoa.jpg?alt=media&token=4c405dcf-ed46-44fe-a5a2-8c58bee20c06',
				alt: 'this is dandelion',
			},
		],
		type: 'website',
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const headersList = headers()

	const pathname = headersList.get('x-x-pathname') || ''
	let content = <>{children}</>
	if (appLayoutExclusive.some((i) => i.startsWith(pathname))) {
		content = (
			<html lang="en">
				<body className={`${geistSans.variable} ${geistMono.variable}`}>
					<div>{children}</div>
				</body>
			</html>
		)
	}
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<AntdRegistry>{content}</AntdRegistry>
			</body>
		</html>
	)
}
